#include "function_pointers.h"

/**
 * int_index - ...
 * @array: ...
 * @size: ...
 * @size: ...
 * @cmp: ...
 * Return: ...
 */
int int_index(int *array, int size, int (*cmp)(int))
	int i = 0;

	if (size > 0)	
